config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :posts do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord

belongs_to :user
belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :photo

  validates :photo, :description, :user_id, presence: true

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_one_attached :photo

  has_many :posts, dependent: :destroy
  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    def authenticate user
        if current_user.nil?
            flash[:error] = 'You must be signed in to view the page.'
            redirect_to login_path
        end  
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
        if @comment.valid?
          redirect_to root_path
        else
          flash[:alert] = "Invalid params"
          redirect_to root_path
        end
      end
    
      <% post.comments.each do |comment| %>
        <p><%= comment.user.name %> <%= comment.text %></p>
        <%= link_to 'Delete', post_comment_path(post_id: post.id, id: comment.id), method: :delete %>
      <% end %>
      
      private
    
      def comment_params
        params.require(:comment).permit(:text, :post_id)
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user, only: [:new, :create]
    before_action :is_owner?, only: [:edit, :update, :destroy]
    def index
        @posts = Post.all.order('created_at DESC')
    end

    def create
        @post = current_user.posts.create(post_params)
        if @post.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
      end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
    @post = Post.find(params[:id])
    @post.update(post_params)
        if @post.valid?
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
    end

    def new
        @post = Post.new
    end

end

    private

    def post_params
        params.require(:post).permit(:user_id, :photo, :caption)
    end

    def is_owner?
        if Post.find(params[:id]).user != current_user
            redirect_to root_path
        end
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid Email or password "
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p id="alert"><%= alert %></p>
<h4>Login</h4>
<%= form_tag sessions_path do |form| %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instapost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3">
        <div class= "row">
          <div class="col-6">
            <a class="navbar-brand" href="/">Instapost</a>
          </div>
          <div class="col-6">
            <ul class="navbar-nav">
              <% if current_user %>
                <li class="nav-item">
                  <%= link_to 'New Post', new_post_path %>
                </li>
                <li>
                  <%= link_to 'Log Out', logout_path, method: "delete" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Sign Up', signup_path %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Log In', login_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<% simple_form_for @post do |f| %>
    <% f.input :photo %>
    <% f.input :description %>
    <% f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<h1>Hello World</h1>
<% @posts.each do |post| %>
  <%= image_tag post.user.photo %>
  <%= post.user.name %>
  <%= image_tag post.photo %>
  <%= post.description %>
  <% if post.user == current_user %>
    <% link_to 'Edit Post', edit_post_path(post.id) %>
    <% link_to 'Delete Post', post_path(post.id), method: :delete %>
  <% end %>
<% end %>

<%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
  <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
  <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: user, url: users_path) do |form| %>
  <!-- Form fields and code -->
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, url: users_path) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>


<div>
  <% if @user.photo.attached? %>
    <%= image_tag @user.photo %>
  <% else %>
    <!-- Provide a default image or placeholder if the user has no photo -->
    <%= image_tag 'sample.png', alt: 'User Image' %>
  <% end %>
</div>

<%= @user.name %>

<%= pluralize(@user.posts.count, 'post') %>


<%= link_to "Logout", logout_path, method: :delete %>